CREATE TABLE jobs (
  id {{PK}},
  user_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  mode VARCHAR(16) NOT NULL DEFAULT 'live',
  state VARCHAR(16) NOT NULL DEFAULT 'draft',
  source_host VARCHAR(255) NOT NULL,
  source_port INTEGER NOT NULL,
  source_encryption VARCHAR(8) NOT NULL,
  source_username_enc TEXT NOT NULL,
  source_password_enc TEXT NOT NULL,
  dest_host VARCHAR(255) NOT NULL,
  dest_port INTEGER NOT NULL,
  dest_encryption VARCHAR(8) NOT NULL,
  dest_username_enc TEXT NOT NULL,
  dest_password_enc TEXT NOT NULL,
  options TEXT NOT NULL,
  total_messages INTEGER NOT NULL DEFAULT 0,
  copied INTEGER NOT NULL DEFAULT 0,
  skipped INTEGER NOT NULL DEFAULT 0,
  failed INTEGER NOT NULL DEFAULT 0,
  current_folder VARCHAR(512) NULL,
  percent INTEGER NOT NULL DEFAULT 0,
  bytes_transferred INTEGER NOT NULL DEFAULT 0,
  last_error TEXT NULL,
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  worker_id VARCHAR(64) NULL,
  locked_at DATETIME NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL
) {{ENGINE}};
CREATE INDEX idx_jobs_user ON jobs(user_id);
CREATE INDEX idx_jobs_state ON jobs(state);
